# Generated by Django 4.2.11 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firebase_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
